has problem
Exception: code: WORKFLOW_INVALID_ARGUMENT
description: "Workflow invalid argument"
details: "Node ID \'unassigned\' does not exist\
 in the graph of nodes"
req_id: "c32f13332604cf75ed6976be955eb3ea"